<a href="https://colab.research.google.com/github/smakesoska1/Julia-Language/blob/main/Labaratorijska_vjezba_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Postavka Julie u Google Colab**

Potrebno je preuzeti ovaj notebook, upload-ovati ga i pokrenuti kôd ispod prilikom kreiranja notebook-a za sve vježbe. Nakon pokretanja, potrebno je restartovati notebook. U *Runtime* kliknite na *Change runtime type* i odaberite Juliu i GPU. Sada možete koristiti Juliu za sve što radite.

U slučaju da vam krene izbacivati greške radi gubitka trenutne sesije izvršite sve naredbe opet i restartujte notebook.




In [ ]:
!curl -sSL "https://julialang-s3.julialang.org/bin/linux/x64/1.5/julia-1.5.2-linux-x86_64.tar.gz" -o julia.tar.gz
!tar -xzf julia.tar.gz -C /usr --strip-components 1
!rm -rf julia.tar.gz*
!julia -e 'using Pkg; pkg"add IJulia; precompile"'
!echo "DONE"

In [ ]:
import Pkg;
 Pkg.add("JuMP")

In [ ]:
using JuMP, Gurobi

In [ ]:
using LinearAlgebra;

In [ ]:
function nadji_pocetno_SZU(c::AbstractMatrix, I::AbstractVector,O::AbstractVector)

brred,brkol = size(c)
A=zeros(Int8,brred,brkol)
i=1
j=1
while((i<=brred) && (j<=brkol))
if I[i]<O[j]
A[i,j]=I[i]
O[j]=O[j]-I[i]
I[i]=0
i=i+1

elseif I[i]>O[j]
A[i,j]=O[j]
I[i]=I[i]-O[j]
O[j]=0
j=j+1

else
A[i,j]=I[i]
I[i]=0
O[j]=0
i=i+1
j=j+1
end
    end

T=sum(A.*c)
return A,T
end

nadji_pocetno_SZU (generic function with 1 method)

Q____Q

Testovi

In [ ]:
c=[8 9 4 6; 6 9 5 3;5 6 7 4]

3×4 Array{Int64,2}:
 8  9  4  6
 6  9  5  3
 5  6  7  4

In [ ]:
I=[100;120;130]

3-element Array{Int64,1}:
 100
 120
 130

In [ ]:
O=[90;125;80;65]

4-element Array{Int64,1}:
  90
 125
  80
  65

In [ ]:
nadji_pocetno_SZU(c,I,O)

(Int8[90 10 0 0; 0 115 5 0; 0 0 75 55], 2615)

Jos testova