<a href="https://colab.research.google.com/github/smakesoska1/Julia-Language/blob/main/Labaratorijska_vjezba_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Postavka Julie u Google Colab**

Potrebno je preuzeti ovaj notebook, upload-ovati ga i pokrenuti kôd ispod prilikom kreiranja notebook-a za sve vježbe. Nakon pokretanja, potrebno je restartovati notebook. U *Runtime* kliknite na *Change runtime type* i odaberite Juliu i GPU. Sada možete koristiti Juliu za sve što radite.

U slučaju da vam krene izbacivati greške radi gubitka trenutne sesije izvršite sve naredbe opet i restartujte notebook.




In [ ]:
!curl -sSL "https://julialang-s3.julialang.org/bin/linux/x64/1.5/julia-1.5.2-linux-x86_64.tar.gz" -o julia.tar.gz
!tar -xzf julia.tar.gz -C /usr --strip-components 1
!rm -rf julia.tar.gz*
!julia -e 'using Pkg; pkg"add IJulia; precompile"'
!echo "DONE"

 Installing known registries into `~/.julia`
######################################################################## 100.0%
      Added registry `General` to `~/.julia/registries/General`
  Resolving package versions...
  Installed ZeroMQ_jll ────── v4.3.2+5
  Installed IJulia ────────── v1.23.1
  Installed MbedTLS_jll ───── v2.16.8+1
  Installed VersionParsing ── v1.2.0
  Installed ZMQ ───────────── v1.2.1
  Installed Artifacts ─────── v1.3.0
  Installed MbedTLS ───────── v1.0.3
  Installed Parsers ───────── v1.0.12
  Installed Conda ─────────── v1.5.0
  Installed JLLWrappers ───── v1.1.3
  Installed JSON ──────────── v0.21.1
  Installed SoftGlobalScope ─ v1.1.0
######################################################################## 100.0%
######################################################################## 100.0%
Updating `~/.julia/environments/v1.5/Project.toml`
  [7073ff75] + IJulia v1.23.1
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [56f22d72] + Artifacts v1.3.0
  

In [ ]:
import Pkg;
 Pkg.add("JuMP")

   Updating registry at `~/.julia/registries/General`
  Resolving package versions...
  Installed Zlib_jll ───────────────────── v1.2.11+18
  Installed ZipFile ────────────────────── v0.9.3
  Installed Compat ─────────────────────── v3.23.0
  Installed CodecBzip2 ─────────────────── v0.7.2
  Installed BenchmarkTools ─────────────── v0.5.0
  Installed MacroTools ─────────────────── v0.5.6
  Installed DataStructures ─────────────── v0.18.8
  Installed JuMP ───────────────────────── v0.21.5
  Installed OrderedCollections ─────────── v1.3.2
  Installed CodecZlib ──────────────────── v0.7.0
  Installed Bzip2_jll ──────────────────── v1.0.6+5
  Installed NaNMath ────────────────────── v0.3.5
  Installed JSONSchema ─────────────────── v0.3.3
  Installed DiffRules ──────────────────── v1.0.2
  Installed MutableArithmetics ─────────── v0.2.12
  Installed URIs ───────────────────────── v1.1.0
  Installed CompilerSupportLibraries_jll ─ v0.3.4+0
  Installed TranscodingStreams ─────────── v0.9.5
  

In [ ]:
using JuMP, Gurobi

┌ Info: Precompiling Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b]
└ @ Base loading.jl:1278
ERROR: LoadError:     Gurobi not properly installed. Please run Pkg.build("Gurobi"). For
    more information go to https://github.com/jump-dev/Gurobi.jl

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at /root/.julia/packages/Gurobi/ntZ45/src/Gurobi.jl:7
 [3] include(::Function, ::Module, ::String) at ./Base.jl:380
 [4] include(::Module, ::String) at ./Base.jl:368
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:331 [inlined]
 [7] eval(::Expr) at ./client.jl:467
 [8] top-level scope at ./none:3
in expression starting at /root/.julia/packages/Gurobi/ntZ45/src/Gurobi.jl:4


LoadError: ignored

In [ ]:
using LinearAlgebra;

In [ ]:
function nadji_pocetno_SZU(c::AbstractMatrix, I::AbstractVector,O::AbstractVector)

brred,brkol = size(c)
A=zeros(Int8,brred,brkol)
i=1
j=1
while((i<=brred) && (j<=brkol))
if I[i]<O[j]
A[i,j]=I[i]
O[j]=O[j]-I[i]
I[i]=0
i=i+1

elseif I[i]>O[j]
A[i,j]=O[j]
I[i]=I[i]-O[j]
O[j]=0
j=j+1

else
A[i,j]=I[i]
I[i]=0
O[j]=0
i=i+1
j=j+1
end
    end

T=sum(A.*c)
return A,T
end

nadji_pocetno_SZU (generic function with 1 method)

Q____Q

Testovi

In [ ]:
c=[8 9 4 6; 6 9 5 3;5 6 7 4]

3×4 Array{Int64,2}:
 8  9  4  6
 6  9  5  3
 5  6  7  4

In [ ]:
I=[100;120;130]

3-element Array{Int64,1}:
 100
 120
 130

In [ ]:
O=[90;125;80;65]

4-element Array{Int64,1}:
  90
 125
  80
  65

In [ ]:
nadji_pocetno_SZU(c,I,O)

(Int8[90 10 0 0; 0 115 5 0; 0 0 75 55], 2615)

Jos testova